spring.application.name=BookStore_BackEnd

# connection to the database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookStore;encrypt=false
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
