spring.application.name=FashionStore_BackEnd
spring.servlet.multipart.max-file-size=60MB
spring.servlet.multipart.max-request-size=60MB
# connection to the database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FashionStore1;encrypt=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


# spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG
#port
server.address=0.0.0.0
server.port=8080
#config Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.timeout=5000

#payment
# VNPAY Configuration
vnpay.vnp_TmnCode=DBHAXRU3
vnpay.vnp_HashSecret=4S8JDLCYG2YOPPPP524BWIKQLFBCHTVE
vnpay.vnp_Url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.vnp_ReturnUrl=http://localhost:5173/payment-result
vnpay.vnp_IpnUrl=http://localhost:8080/api/payment/vnpay-ipn

#Ngân hàng	NCB
#S? th?	9704198526191432198
#Tên ch? th?	9704198526191432198
#Ngày phát hành	07/15
#M?t kh?u OTP	123456