spring.application.name=FashionStore_BackEnd

# connection to the database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FashionStore1;encrypt=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG

#config Mail